// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: chart.proto
// Protobuf C++ Version: 6.33.0

#include "chart.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace webrtc {
namespace analytics {

inline constexpr TickLabel::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        label_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        value_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TickLabel::TickLabel(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(TickLabel_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TickLabelDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TickLabelDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TickLabelDefaultTypeInternal() {}
  union {
    TickLabel _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT_WITH_PTR
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TickLabelDefaultTypeInternal _TickLabel_default_instance_;

inline constexpr DataSet::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        x_values_{},
        y_values_{},
        label_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        style_{static_cast< ::webrtc::analytics::ChartStyle_Type >(0)},
        highlight_points_{false} {}

template <typename>
PROTOBUF_CONSTEXPR DataSet::DataSet(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(DataSet_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DataSetDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DataSetDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DataSetDefaultTypeInternal() {}
  union {
    DataSet _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT_WITH_PTR
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DataSetDefaultTypeInternal _DataSet_default_instance_;

inline constexpr Chart::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        data_sets_{},
        yaxis_tick_labels_{},
        xaxis_label_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        yaxis_label_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        title_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        xaxis_min_{0},
        xaxis_max_{0},
        yaxis_min_{0},
        yaxis_max_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Chart::Chart(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(Chart_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ChartDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChartDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChartDefaultTypeInternal() {}
  union {
    Chart _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT_WITH_PTR
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChartDefaultTypeInternal _Chart_default_instance_;

inline constexpr ChartCollection::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        charts_{},
        calltime_to_utc_ms_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR ChartCollection::ChartCollection(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(ChartCollection_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ChartCollectionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChartCollectionDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChartCollectionDefaultTypeInternal() {}
  union {
    ChartCollection _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT_WITH_PTR
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChartCollectionDefaultTypeInternal _ChartCollection_default_instance_;
}  // namespace analytics
}  // namespace webrtc
namespace webrtc {
namespace analytics {
// ===================================================================

class DataSet::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<DataSet>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(DataSet, _impl_._has_bits_);
};

DataSet::DataSet(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, DataSet_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:webrtc.analytics.DataSet)
}
PROTOBUF_NDEBUG_INLINE DataSet::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::webrtc::analytics::DataSet& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        x_values_{visibility, arena, from.x_values_},
        y_values_{visibility, arena, from.y_values_},
        label_(arena, from.label_) {}

DataSet::DataSet(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const DataSet& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, DataSet_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  DataSet* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, style_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, style_),
           offsetof(Impl_, highlight_points_) -
               offsetof(Impl_, style_) +
               sizeof(Impl_::highlight_points_));

  // @@protoc_insertion_point(copy_constructor:webrtc.analytics.DataSet)
}
PROTOBUF_NDEBUG_INLINE DataSet::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        x_values_{visibility, arena},
        y_values_{visibility, arena},
        label_(arena) {}

inline void DataSet::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, style_),
           0,
           offsetof(Impl_, highlight_points_) -
               offsetof(Impl_, style_) +
               sizeof(Impl_::highlight_points_));
}
DataSet::~DataSet() {
  // @@protoc_insertion_point(destructor:webrtc.analytics.DataSet)
  SharedDtor(*this);
}
inline void DataSet::SharedDtor(MessageLite& self) {
  DataSet& this_ = static_cast<DataSet&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.label_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL DataSet::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) DataSet(arena);
}
constexpr auto DataSet::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(DataSet, _impl_.x_values_) +
          decltype(DataSet::_impl_.x_values_)::
              InternalGetArenaOffset(
                  ::google::protobuf::MessageLite::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(DataSet, _impl_.y_values_) +
          decltype(DataSet::_impl_.y_values_)::
              InternalGetArenaOffset(
                  ::google::protobuf::MessageLite::internal_visibility()),
  });
  if constexpr (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(DataSet), alignof(DataSet), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&DataSet::PlacementNew_,
                                 sizeof(DataSet),
                                 alignof(DataSet));
  }
}
constexpr auto DataSet::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<25>{
      {
          &_DataSet_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &DataSet::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<DataSet>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &DataSet::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<DataSet>(), &DataSet::ByteSizeLong,
              &DataSet::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(DataSet, _impl_._cached_size_),
          true,
      },
      "webrtc.analytics.DataSet",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<25> DataSet_class_data_ =
    DataSet::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
DataSet::GetClassData() const {
  return DataSet_class_data_.base();
}
PROTOBUF_CONSTINIT_WITH_PTR PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 38, 2>
DataSet::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(DataSet, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    DataSet_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::webrtc::analytics::DataSet>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // repeated float x_values = 1;
    {::_pbi::TcParser::FastF32P1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(DataSet, _impl_.x_values_)}},
    // repeated float y_values = 2;
    {::_pbi::TcParser::FastF32P1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(DataSet, _impl_.y_values_)}},
    // string label = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 2, 0,
      PROTOBUF_FIELD_OFFSET(DataSet, _impl_.label_)}},
    // .webrtc.analytics.ChartStyle.Type style = 4;
    {::_pbi::TcParser::FastV32S1,
     {32, 3, 0,
      PROTOBUF_FIELD_OFFSET(DataSet, _impl_.style_)}},
    // bool highlight_points = 5;
    {::_pbi::TcParser::FastV8S1,
     {40, 4, 0,
      PROTOBUF_FIELD_OFFSET(DataSet, _impl_.highlight_points_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated float x_values = 1;
    {PROTOBUF_FIELD_OFFSET(DataSet, _impl_.x_values_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // repeated float y_values = 2;
    {PROTOBUF_FIELD_OFFSET(DataSet, _impl_.y_values_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // string label = 3;
    {PROTOBUF_FIELD_OFFSET(DataSet, _impl_.label_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .webrtc.analytics.ChartStyle.Type style = 4;
    {PROTOBUF_FIELD_OFFSET(DataSet, _impl_.style_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // bool highlight_points = 5;
    {PROTOBUF_FIELD_OFFSET(DataSet, _impl_.highlight_points_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\30\0\0\5\0\0\0\0"
    "webrtc.analytics.DataSet"
    "label"
  }},
};
PROTOBUF_NOINLINE void DataSet::Clear() {
// @@protoc_insertion_point(message_clear_start:webrtc.analytics.DataSet)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.x_values_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _impl_.y_values_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.label_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000018U)) {
    ::memset(&_impl_.style_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.highlight_points_) -
        reinterpret_cast<char*>(&_impl_.style_)) + sizeof(_impl_.highlight_points_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL DataSet::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const DataSet& this_ = static_cast<const DataSet&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL DataSet::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const DataSet& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:webrtc.analytics.DataSet)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated float x_values = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    if (this_._internal_x_values_size() > 0) {
      target = stream->WriteFixedPacked(1, this_._internal_x_values(), target);
    }
  }

  // repeated float y_values = 2;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
    if (this_._internal_y_values_size() > 0) {
      target = stream->WriteFixedPacked(2, this_._internal_y_values(), target);
    }
  }

  // string label = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_label().empty()) {
      const ::std::string& _s = this_._internal_label();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "webrtc.analytics.DataSet.label");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // .webrtc.analytics.ChartStyle.Type style = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_style() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          4, this_._internal_style(), target);
    }
  }

  // bool highlight_points = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_highlight_points() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          5, this_._internal_highlight_points(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:webrtc.analytics.DataSet)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t DataSet::ByteSizeLong(const MessageLite& base) {
  const DataSet& this_ = static_cast<const DataSet&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t DataSet::ByteSizeLong() const {
  const DataSet& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:webrtc.analytics.DataSet)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // repeated float x_values = 1;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      ::size_t data_size = ::size_t{4} *
          ::_pbi::FromIntSize(this_._internal_x_values_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
    // repeated float y_values = 2;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      ::size_t data_size = ::size_t{4} *
          ::_pbi::FromIntSize(this_._internal_y_values_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
    // string label = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_label().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_label());
      }
    }
    // .webrtc.analytics.ChartStyle.Type style = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_style() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_style());
      }
    }
    // bool highlight_points = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_highlight_points() != 0) {
        total_size += 2;
      }
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void DataSet::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<DataSet*>(&to_msg);
  auto& from = static_cast<const DataSet&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:webrtc.analytics.DataSet)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_x_values()->MergeFrom(from._internal_x_values());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _this->_internal_mutable_y_values()->MergeFrom(from._internal_y_values());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_label().empty()) {
        _this->_internal_set_label(from._internal_label());
      } else {
        if (_this->_impl_.label_.IsDefault()) {
          _this->_internal_set_label("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_style() != 0) {
        _this->_impl_.style_ = from._impl_.style_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_highlight_points() != 0) {
        _this->_impl_.highlight_points_ = from._impl_.highlight_points_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void DataSet::CopyFrom(const DataSet& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:webrtc.analytics.DataSet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DataSet::InternalSwap(DataSet* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.x_values_.InternalSwap(&other->_impl_.x_values_);
  _impl_.y_values_.InternalSwap(&other->_impl_.y_values_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.label_, &other->_impl_.label_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DataSet, _impl_.highlight_points_)
      + sizeof(DataSet::_impl_.highlight_points_)
      - PROTOBUF_FIELD_OFFSET(DataSet, _impl_.style_)>(
          reinterpret_cast<char*>(&_impl_.style_),
          reinterpret_cast<char*>(&other->_impl_.style_));
}

// ===================================================================

class TickLabel::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<TickLabel>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(TickLabel, _impl_._has_bits_);
};

TickLabel::TickLabel(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, TickLabel_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:webrtc.analytics.TickLabel)
}
PROTOBUF_NDEBUG_INLINE TickLabel::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::webrtc::analytics::TickLabel& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        label_(arena, from.label_) {}

TickLabel::TickLabel(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const TickLabel& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, TickLabel_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TickLabel* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.value_ = from._impl_.value_;

  // @@protoc_insertion_point(copy_constructor:webrtc.analytics.TickLabel)
}
PROTOBUF_NDEBUG_INLINE TickLabel::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        label_(arena) {}

inline void TickLabel::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.value_ = {};
}
TickLabel::~TickLabel() {
  // @@protoc_insertion_point(destructor:webrtc.analytics.TickLabel)
  SharedDtor(*this);
}
inline void TickLabel::SharedDtor(MessageLite& self) {
  TickLabel& this_ = static_cast<TickLabel&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.label_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL TickLabel::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) TickLabel(arena);
}
constexpr auto TickLabel::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(TickLabel),
                                            alignof(TickLabel));
}
constexpr auto TickLabel::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<27>{
      {
          &_TickLabel_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &TickLabel::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<TickLabel>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &TickLabel::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<TickLabel>(), &TickLabel::ByteSizeLong,
              &TickLabel::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(TickLabel, _impl_._cached_size_),
          true,
      },
      "webrtc.analytics.TickLabel",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<27> TickLabel_class_data_ =
    TickLabel::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
TickLabel::GetClassData() const {
  return TickLabel_class_data_.base();
}
PROTOBUF_CONSTINIT_WITH_PTR PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 40, 2>
TickLabel::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(TickLabel, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    TickLabel_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::webrtc::analytics::TickLabel>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string label = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(TickLabel, _impl_.label_)}},
    // float value = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 1, 0,
      PROTOBUF_FIELD_OFFSET(TickLabel, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // float value = 1;
    {PROTOBUF_FIELD_OFFSET(TickLabel, _impl_.value_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // string label = 2;
    {PROTOBUF_FIELD_OFFSET(TickLabel, _impl_.label_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\32\0\5\0\0\0\0\0"
    "webrtc.analytics.TickLabel"
    "label"
  }},
};
PROTOBUF_NOINLINE void TickLabel::Clear() {
// @@protoc_insertion_point(message_clear_start:webrtc.analytics.TickLabel)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.label_.ClearNonDefaultToEmpty();
  }
  _impl_.value_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL TickLabel::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const TickLabel& this_ = static_cast<const TickLabel&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL TickLabel::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const TickLabel& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:webrtc.analytics.TickLabel)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // float value = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_value()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          1, this_._internal_value(), target);
    }
  }

  // string label = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_label().empty()) {
      const ::std::string& _s = this_._internal_label();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "webrtc.analytics.TickLabel.label");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:webrtc.analytics.TickLabel)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t TickLabel::ByteSizeLong(const MessageLite& base) {
  const TickLabel& this_ = static_cast<const TickLabel&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t TickLabel::ByteSizeLong() const {
  const TickLabel& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:webrtc.analytics.TickLabel)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string label = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_label().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_label());
      }
    }
    // float value = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_value()) != 0) {
        total_size += 5;
      }
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void TickLabel::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<TickLabel*>(&to_msg);
  auto& from = static_cast<const TickLabel&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:webrtc.analytics.TickLabel)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_label().empty()) {
        _this->_internal_set_label(from._internal_label());
      } else {
        if (_this->_impl_.label_.IsDefault()) {
          _this->_internal_set_label("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (::absl::bit_cast<::uint32_t>(from._internal_value()) != 0) {
        _this->_impl_.value_ = from._impl_.value_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void TickLabel::CopyFrom(const TickLabel& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:webrtc.analytics.TickLabel)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TickLabel::InternalSwap(TickLabel* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.label_, &other->_impl_.label_, arena);
  swap(_impl_.value_, other->_impl_.value_);
}

// ===================================================================

class Chart::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Chart>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Chart, _impl_._has_bits_);
};

Chart::Chart(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, Chart_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:webrtc.analytics.Chart)
}
PROTOBUF_NDEBUG_INLINE Chart::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::webrtc::analytics::Chart& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        data_sets_{visibility, arena, from.data_sets_},
        yaxis_tick_labels_{visibility, arena, from.yaxis_tick_labels_},
        xaxis_label_(arena, from.xaxis_label_),
        yaxis_label_(arena, from.yaxis_label_),
        title_(arena, from.title_),
        id_(arena, from.id_) {}

Chart::Chart(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Chart& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, Chart_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Chart* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, xaxis_min_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, xaxis_min_),
           offsetof(Impl_, yaxis_max_) -
               offsetof(Impl_, xaxis_min_) +
               sizeof(Impl_::yaxis_max_));

  // @@protoc_insertion_point(copy_constructor:webrtc.analytics.Chart)
}
PROTOBUF_NDEBUG_INLINE Chart::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        data_sets_{visibility, arena},
        yaxis_tick_labels_{visibility, arena},
        xaxis_label_(arena),
        yaxis_label_(arena),
        title_(arena),
        id_(arena) {}

inline void Chart::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, xaxis_min_),
           0,
           offsetof(Impl_, yaxis_max_) -
               offsetof(Impl_, xaxis_min_) +
               sizeof(Impl_::yaxis_max_));
}
Chart::~Chart() {
  // @@protoc_insertion_point(destructor:webrtc.analytics.Chart)
  SharedDtor(*this);
}
inline void Chart::SharedDtor(MessageLite& self) {
  Chart& this_ = static_cast<Chart&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.xaxis_label_.Destroy();
  this_._impl_.yaxis_label_.Destroy();
  this_._impl_.title_.Destroy();
  this_._impl_.id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Chart::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Chart(arena);
}
constexpr auto Chart::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Chart, _impl_.data_sets_) +
          decltype(Chart::_impl_.data_sets_)::
              InternalGetArenaOffset(
                  ::google::protobuf::MessageLite::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(Chart, _impl_.yaxis_tick_labels_) +
          decltype(Chart::_impl_.yaxis_tick_labels_)::
              InternalGetArenaOffset(
                  ::google::protobuf::MessageLite::internal_visibility()),
  });
  if constexpr (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(Chart), alignof(Chart), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Chart::PlacementNew_,
                                 sizeof(Chart),
                                 alignof(Chart));
  }
}
constexpr auto Chart::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<23>{
      {
          &_Chart_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Chart::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<Chart>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Chart::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<Chart>(), &Chart::ByteSizeLong,
              &Chart::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Chart, _impl_._cached_size_),
          true,
      },
      "webrtc.analytics.Chart",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<23> Chart_class_data_ =
    Chart::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Chart::GetClassData() const {
  return Chart_class_data_.base();
}
PROTOBUF_CONSTINIT_WITH_PTR PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 10, 2, 68, 2>
Chart::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Chart, _impl_._has_bits_),
    0, // no _extensions_
    10, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966272,  // skipmap
    offsetof(decltype(_table_), field_entries),
    10,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Chart_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::webrtc::analytics::Chart>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // repeated .webrtc.analytics.DataSet data_sets = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(Chart, _impl_.data_sets_)}},
    // float xaxis_min = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 6, 0,
      PROTOBUF_FIELD_OFFSET(Chart, _impl_.xaxis_min_)}},
    // float xaxis_max = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 7, 0,
      PROTOBUF_FIELD_OFFSET(Chart, _impl_.xaxis_max_)}},
    // string xaxis_label = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 2, 0,
      PROTOBUF_FIELD_OFFSET(Chart, _impl_.xaxis_label_)}},
    // float yaxis_min = 5;
    {::_pbi::TcParser::FastF32S1,
     {45, 8, 0,
      PROTOBUF_FIELD_OFFSET(Chart, _impl_.yaxis_min_)}},
    // float yaxis_max = 6;
    {::_pbi::TcParser::FastF32S1,
     {53, 9, 0,
      PROTOBUF_FIELD_OFFSET(Chart, _impl_.yaxis_max_)}},
    // string yaxis_label = 7;
    {::_pbi::TcParser::FastUS1,
     {58, 3, 0,
      PROTOBUF_FIELD_OFFSET(Chart, _impl_.yaxis_label_)}},
    // string title = 8;
    {::_pbi::TcParser::FastUS1,
     {66, 4, 0,
      PROTOBUF_FIELD_OFFSET(Chart, _impl_.title_)}},
    // string id = 9;
    {::_pbi::TcParser::FastUS1,
     {74, 5, 0,
      PROTOBUF_FIELD_OFFSET(Chart, _impl_.id_)}},
    // repeated .webrtc.analytics.TickLabel yaxis_tick_labels = 10;
    {::_pbi::TcParser::FastMtR1,
     {82, 1, 1,
      PROTOBUF_FIELD_OFFSET(Chart, _impl_.yaxis_tick_labels_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .webrtc.analytics.DataSet data_sets = 1;
    {PROTOBUF_FIELD_OFFSET(Chart, _impl_.data_sets_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // float xaxis_min = 2;
    {PROTOBUF_FIELD_OFFSET(Chart, _impl_.xaxis_min_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // float xaxis_max = 3;
    {PROTOBUF_FIELD_OFFSET(Chart, _impl_.xaxis_max_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // string xaxis_label = 4;
    {PROTOBUF_FIELD_OFFSET(Chart, _impl_.xaxis_label_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // float yaxis_min = 5;
    {PROTOBUF_FIELD_OFFSET(Chart, _impl_.yaxis_min_), _Internal::kHasBitsOffset + 8, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // float yaxis_max = 6;
    {PROTOBUF_FIELD_OFFSET(Chart, _impl_.yaxis_max_), _Internal::kHasBitsOffset + 9, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // string yaxis_label = 7;
    {PROTOBUF_FIELD_OFFSET(Chart, _impl_.yaxis_label_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string title = 8;
    {PROTOBUF_FIELD_OFFSET(Chart, _impl_.title_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string id = 9;
    {PROTOBUF_FIELD_OFFSET(Chart, _impl_.id_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated .webrtc.analytics.TickLabel yaxis_tick_labels = 10;
    {PROTOBUF_FIELD_OFFSET(Chart, _impl_.yaxis_tick_labels_), _Internal::kHasBitsOffset + 1, 1, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::webrtc::analytics::DataSet>()},
      {::_pbi::TcParser::GetTable<::webrtc::analytics::TickLabel>()},
  }},
  {{
    "\26\0\0\0\13\0\0\13\5\2\0\0\0\0\0\0"
    "webrtc.analytics.Chart"
    "xaxis_label"
    "yaxis_label"
    "title"
    "id"
  }},
};
PROTOBUF_NOINLINE void Chart::Clear() {
// @@protoc_insertion_point(message_clear_start:webrtc.analytics.Chart)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.data_sets_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _impl_.yaxis_tick_labels_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.xaxis_label_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _impl_.yaxis_label_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _impl_.title_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      _impl_.id_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x000000c0U)) {
    ::memset(&_impl_.xaxis_min_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.xaxis_max_) -
        reinterpret_cast<char*>(&_impl_.xaxis_min_)) + sizeof(_impl_.xaxis_max_));
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000300U)) {
    ::memset(&_impl_.yaxis_min_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.yaxis_max_) -
        reinterpret_cast<char*>(&_impl_.yaxis_min_)) + sizeof(_impl_.yaxis_max_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Chart::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Chart& this_ = static_cast<const Chart&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Chart::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Chart& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:webrtc.analytics.Chart)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated .webrtc.analytics.DataSet data_sets = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_data_sets_size());
         i < n; i++) {
      const auto& repfield = this_._internal_data_sets().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              1, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // float xaxis_min = 2;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_xaxis_min()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          2, this_._internal_xaxis_min(), target);
    }
  }

  // float xaxis_max = 3;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_xaxis_max()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          3, this_._internal_xaxis_max(), target);
    }
  }

  // string xaxis_label = 4;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_xaxis_label().empty()) {
      const ::std::string& _s = this_._internal_xaxis_label();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "webrtc.analytics.Chart.xaxis_label");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  // float yaxis_min = 5;
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_yaxis_min()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          5, this_._internal_yaxis_min(), target);
    }
  }

  // float yaxis_max = 6;
  if (CheckHasBit(cached_has_bits, 0x00000200U)) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_yaxis_max()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          6, this_._internal_yaxis_max(), target);
    }
  }

  // string yaxis_label = 7;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (!this_._internal_yaxis_label().empty()) {
      const ::std::string& _s = this_._internal_yaxis_label();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "webrtc.analytics.Chart.yaxis_label");
      target = stream->WriteStringMaybeAliased(7, _s, target);
    }
  }

  // string title = 8;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (!this_._internal_title().empty()) {
      const ::std::string& _s = this_._internal_title();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "webrtc.analytics.Chart.title");
      target = stream->WriteStringMaybeAliased(8, _s, target);
    }
  }

  // string id = 9;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (!this_._internal_id().empty()) {
      const ::std::string& _s = this_._internal_id();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "webrtc.analytics.Chart.id");
      target = stream->WriteStringMaybeAliased(9, _s, target);
    }
  }

  // repeated .webrtc.analytics.TickLabel yaxis_tick_labels = 10;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_yaxis_tick_labels_size());
         i < n; i++) {
      const auto& repfield = this_._internal_yaxis_tick_labels().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              10, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:webrtc.analytics.Chart)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Chart::ByteSizeLong(const MessageLite& base) {
  const Chart& this_ = static_cast<const Chart&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Chart::ByteSizeLong() const {
  const Chart& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:webrtc.analytics.Chart)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // repeated .webrtc.analytics.DataSet data_sets = 1;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_data_sets_size();
      for (const auto& msg : this_._internal_data_sets()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // repeated .webrtc.analytics.TickLabel yaxis_tick_labels = 10;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      total_size += 1UL * this_._internal_yaxis_tick_labels_size();
      for (const auto& msg : this_._internal_yaxis_tick_labels()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // string xaxis_label = 4;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_xaxis_label().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_xaxis_label());
      }
    }
    // string yaxis_label = 7;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!this_._internal_yaxis_label().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_yaxis_label());
      }
    }
    // string title = 8;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (!this_._internal_title().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_title());
      }
    }
    // string id = 9;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (!this_._internal_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_id());
      }
    }
    // float xaxis_min = 2;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_xaxis_min()) != 0) {
        total_size += 5;
      }
    }
    // float xaxis_max = 3;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_xaxis_max()) != 0) {
        total_size += 5;
      }
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000300U)) {
    // float yaxis_min = 5;
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_yaxis_min()) != 0) {
        total_size += 5;
      }
    }
    // float yaxis_max = 6;
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_yaxis_max()) != 0) {
        total_size += 5;
      }
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void Chart::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Chart*>(&to_msg);
  auto& from = static_cast<const Chart&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:webrtc.analytics.Chart)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_data_sets()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_data_sets());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _this->_internal_mutable_yaxis_tick_labels()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_yaxis_tick_labels());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_xaxis_label().empty()) {
        _this->_internal_set_xaxis_label(from._internal_xaxis_label());
      } else {
        if (_this->_impl_.xaxis_label_.IsDefault()) {
          _this->_internal_set_xaxis_label("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!from._internal_yaxis_label().empty()) {
        _this->_internal_set_yaxis_label(from._internal_yaxis_label());
      } else {
        if (_this->_impl_.yaxis_label_.IsDefault()) {
          _this->_internal_set_yaxis_label("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (!from._internal_title().empty()) {
        _this->_internal_set_title(from._internal_title());
      } else {
        if (_this->_impl_.title_.IsDefault()) {
          _this->_internal_set_title("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (!from._internal_id().empty()) {
        _this->_internal_set_id(from._internal_id());
      } else {
        if (_this->_impl_.id_.IsDefault()) {
          _this->_internal_set_id("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (::absl::bit_cast<::uint32_t>(from._internal_xaxis_min()) != 0) {
        _this->_impl_.xaxis_min_ = from._impl_.xaxis_min_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (::absl::bit_cast<::uint32_t>(from._internal_xaxis_max()) != 0) {
        _this->_impl_.xaxis_max_ = from._impl_.xaxis_max_;
      }
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000300U)) {
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      if (::absl::bit_cast<::uint32_t>(from._internal_yaxis_min()) != 0) {
        _this->_impl_.yaxis_min_ = from._impl_.yaxis_min_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      if (::absl::bit_cast<::uint32_t>(from._internal_yaxis_max()) != 0) {
        _this->_impl_.yaxis_max_ = from._impl_.yaxis_max_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void Chart::CopyFrom(const Chart& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:webrtc.analytics.Chart)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Chart::InternalSwap(Chart* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.data_sets_.InternalSwap(&other->_impl_.data_sets_);
  _impl_.yaxis_tick_labels_.InternalSwap(&other->_impl_.yaxis_tick_labels_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.xaxis_label_, &other->_impl_.xaxis_label_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.yaxis_label_, &other->_impl_.yaxis_label_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.title_, &other->_impl_.title_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.id_, &other->_impl_.id_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Chart, _impl_.yaxis_max_)
      + sizeof(Chart::_impl_.yaxis_max_)
      - PROTOBUF_FIELD_OFFSET(Chart, _impl_.xaxis_min_)>(
          reinterpret_cast<char*>(&_impl_.xaxis_min_),
          reinterpret_cast<char*>(&other->_impl_.xaxis_min_));
}

// ===================================================================

class ChartCollection::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ChartCollection>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ChartCollection, _impl_._has_bits_);
};

ChartCollection::ChartCollection(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, ChartCollection_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:webrtc.analytics.ChartCollection)
}
PROTOBUF_NDEBUG_INLINE ChartCollection::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::webrtc::analytics::ChartCollection& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        charts_{visibility, arena, from.charts_} {}

ChartCollection::ChartCollection(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ChartCollection& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, ChartCollection_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ChartCollection* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.calltime_to_utc_ms_ = from._impl_.calltime_to_utc_ms_;

  // @@protoc_insertion_point(copy_constructor:webrtc.analytics.ChartCollection)
}
PROTOBUF_NDEBUG_INLINE ChartCollection::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        charts_{visibility, arena} {}

inline void ChartCollection::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.calltime_to_utc_ms_ = {};
}
ChartCollection::~ChartCollection() {
  // @@protoc_insertion_point(destructor:webrtc.analytics.ChartCollection)
  SharedDtor(*this);
}
inline void ChartCollection::SharedDtor(MessageLite& self) {
  ChartCollection& this_ = static_cast<ChartCollection&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ChartCollection::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ChartCollection(arena);
}
constexpr auto ChartCollection::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(ChartCollection, _impl_.charts_) +
          decltype(ChartCollection::_impl_.charts_)::
              InternalGetArenaOffset(
                  ::google::protobuf::MessageLite::internal_visibility()),
  });
  if constexpr (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(ChartCollection), alignof(ChartCollection), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&ChartCollection::PlacementNew_,
                                 sizeof(ChartCollection),
                                 alignof(ChartCollection));
  }
}
constexpr auto ChartCollection::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<33>{
      {
          &_ChartCollection_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ChartCollection::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<ChartCollection>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ChartCollection::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<ChartCollection>(), &ChartCollection::ByteSizeLong,
              &ChartCollection::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ChartCollection, _impl_._cached_size_),
          true,
      },
      "webrtc.analytics.ChartCollection",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<33> ChartCollection_class_data_ =
    ChartCollection::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ChartCollection::GetClassData() const {
  return ChartCollection_class_data_.base();
}
PROTOBUF_CONSTINIT_WITH_PTR PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2>
ChartCollection::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ChartCollection, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    ChartCollection_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::webrtc::analytics::ChartCollection>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int64 calltime_to_utc_ms = 2;
    {::_pbi::TcParser::FastV64S1,
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(ChartCollection, _impl_.calltime_to_utc_ms_)}},
    // repeated .webrtc.analytics.Chart charts = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(ChartCollection, _impl_.charts_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .webrtc.analytics.Chart charts = 1;
    {PROTOBUF_FIELD_OFFSET(ChartCollection, _impl_.charts_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // int64 calltime_to_utc_ms = 2;
    {PROTOBUF_FIELD_OFFSET(ChartCollection, _impl_.calltime_to_utc_ms_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::webrtc::analytics::Chart>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void ChartCollection::Clear() {
// @@protoc_insertion_point(message_clear_start:webrtc.analytics.ChartCollection)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.charts_.Clear();
  }
  _impl_.calltime_to_utc_ms_ = ::int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ChartCollection::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ChartCollection& this_ = static_cast<const ChartCollection&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ChartCollection::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ChartCollection& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:webrtc.analytics.ChartCollection)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated .webrtc.analytics.Chart charts = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_charts_size());
         i < n; i++) {
      const auto& repfield = this_._internal_charts().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              1, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // int64 calltime_to_utc_ms = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_calltime_to_utc_ms() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<2>(
              stream, this_._internal_calltime_to_utc_ms(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:webrtc.analytics.ChartCollection)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ChartCollection::ByteSizeLong(const MessageLite& base) {
  const ChartCollection& this_ = static_cast<const ChartCollection&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ChartCollection::ByteSizeLong() const {
  const ChartCollection& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:webrtc.analytics.ChartCollection)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // repeated .webrtc.analytics.Chart charts = 1;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_charts_size();
      for (const auto& msg : this_._internal_charts()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // int64 calltime_to_utc_ms = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_calltime_to_utc_ms() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_calltime_to_utc_ms());
      }
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void ChartCollection::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<ChartCollection*>(&to_msg);
  auto& from = static_cast<const ChartCollection&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:webrtc.analytics.ChartCollection)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_charts()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_charts());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_calltime_to_utc_ms() != 0) {
        _this->_impl_.calltime_to_utc_ms_ = from._impl_.calltime_to_utc_ms_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void ChartCollection::CopyFrom(const ChartCollection& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:webrtc.analytics.ChartCollection)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ChartCollection::InternalSwap(ChartCollection* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.charts_.InternalSwap(&other->_impl_.charts_);
  swap(_impl_.calltime_to_utc_ms_, other->_impl_.calltime_to_utc_ms_);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace analytics
}  // namespace webrtc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
