// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: debug_dump.proto
// Protobuf C++ Version: 6.33.0

#include "debug_dump.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace webrtc {
namespace audio_network_adaptor {
namespace debug_dump {

inline constexpr NetworkMetrics::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        uplink_bandwidth_bps_{0},
        uplink_packet_loss_fraction_{0},
        target_audio_bitrate_bps_{0},
        rtt_ms_{0},
        uplink_recoverable_packet_loss_fraction_{0} {}

template <typename>
PROTOBUF_CONSTEXPR NetworkMetrics::NetworkMetrics(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(NetworkMetrics_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NetworkMetricsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NetworkMetricsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NetworkMetricsDefaultTypeInternal() {}
  union {
    NetworkMetrics _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT_WITH_PTR
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NetworkMetricsDefaultTypeInternal _NetworkMetrics_default_instance_;

inline constexpr EncoderRuntimeConfig::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        bitrate_bps_{0},
        frame_length_ms_{0},
        uplink_packet_loss_fraction_{0},
        enable_fec_{false},
        enable_dtx_{false},
        num_channels_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR EncoderRuntimeConfig::EncoderRuntimeConfig(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(EncoderRuntimeConfig_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EncoderRuntimeConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EncoderRuntimeConfigDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EncoderRuntimeConfigDefaultTypeInternal() {}
  union {
    EncoderRuntimeConfig _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT_WITH_PTR
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EncoderRuntimeConfigDefaultTypeInternal _EncoderRuntimeConfig_default_instance_;

inline constexpr Event::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        network_metrics_{nullptr},
        encoder_runtime_config_{nullptr},
        controller_manager_config_{nullptr},
        type_{static_cast< ::webrtc::audio_network_adaptor::debug_dump::Event_Type >(0)},
        timestamp_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR Event::Event(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(Event_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EventDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EventDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EventDefaultTypeInternal() {}
  union {
    Event _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT_WITH_PTR
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EventDefaultTypeInternal _Event_default_instance_;
}  // namespace debug_dump
}  // namespace audio_network_adaptor
}  // namespace webrtc
namespace webrtc {
namespace audio_network_adaptor {
namespace debug_dump {
PROTOBUF_CONSTINIT const uint32_t Event_Type_internal_data_[] = {
    196608u, 0u, };
static ::google::protobuf::internal::ExplicitlyConstructed<::std::string>
    Event_Type_strings[3] = {};

static const char Event_Type_names[] = {
    "CONTROLLER_MANAGER_CONFIG"
    "ENCODER_RUNTIME_CONFIG"
    "NETWORK_METRICS"
};

static const ::google::protobuf::internal::EnumEntry Event_Type_entries[] = {
    {{&Event_Type_names[0], 25}, 2},
    {{&Event_Type_names[25], 22}, 1},
    {{&Event_Type_names[47], 15}, 0},
};

static const int Event_Type_entries_by_number[] = {
    2,  // 0 -> NETWORK_METRICS
    1,  // 1 -> ENCODER_RUNTIME_CONFIG
    0,  // 2 -> CONTROLLER_MANAGER_CONFIG
};

const ::std::string& Event_Type_Name(Event_Type value) {
  static const bool kDummy = ::google::protobuf::internal::InitializeEnumStrings(
      Event_Type_entries, Event_Type_entries_by_number, 3,
      Event_Type_strings);
  (void)kDummy;

  int idx = ::google::protobuf::internal::LookUpEnumName(Event_Type_entries,
                                  Event_Type_entries_by_number,
                                  3, value);
  return idx == -1 ? ::google::protobuf::internal::GetEmptyString() : Event_Type_strings[idx].get();
}

bool Event_Type_Parse(::absl::string_view name, Event_Type* PROTOBUF_NONNULL value) {
  int int_value;
  bool success = ::google::protobuf::internal::LookUpEnumValue(
      Event_Type_entries, 3, name, &int_value);
  if (success) {
    *value = static_cast<Event_Type>(int_value);
  }
  return success;
}
// ===================================================================

class NetworkMetrics::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<NetworkMetrics>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(NetworkMetrics, _impl_._has_bits_);
};

NetworkMetrics::NetworkMetrics(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, NetworkMetrics_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:webrtc.audio_network_adaptor.debug_dump.NetworkMetrics)
}
NetworkMetrics::NetworkMetrics(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const NetworkMetrics& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, NetworkMetrics_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE NetworkMetrics::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void NetworkMetrics::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, uplink_bandwidth_bps_),
           0,
           offsetof(Impl_, uplink_recoverable_packet_loss_fraction_) -
               offsetof(Impl_, uplink_bandwidth_bps_) +
               sizeof(Impl_::uplink_recoverable_packet_loss_fraction_));
}
NetworkMetrics::~NetworkMetrics() {
  // @@protoc_insertion_point(destructor:webrtc.audio_network_adaptor.debug_dump.NetworkMetrics)
  SharedDtor(*this);
}
inline void NetworkMetrics::SharedDtor(MessageLite& self) {
  NetworkMetrics& this_ = static_cast<NetworkMetrics&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL NetworkMetrics::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) NetworkMetrics(arena);
}
constexpr auto NetworkMetrics::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(NetworkMetrics),
                                            alignof(NetworkMetrics));
}
constexpr auto NetworkMetrics::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<55>{
      {
          &_NetworkMetrics_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &NetworkMetrics::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<NetworkMetrics>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &NetworkMetrics::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<NetworkMetrics>(), &NetworkMetrics::ByteSizeLong,
              &NetworkMetrics::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(NetworkMetrics, _impl_._cached_size_),
          true,
      },
      "webrtc.audio_network_adaptor.debug_dump.NetworkMetrics",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<55> NetworkMetrics_class_data_ =
    NetworkMetrics::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NetworkMetrics::GetClassData() const {
  return NetworkMetrics_class_data_.base();
}
PROTOBUF_CONSTINIT_WITH_PTR PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 0, 2>
NetworkMetrics::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(NetworkMetrics, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    NetworkMetrics_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::webrtc::audio_network_adaptor::debug_dump::NetworkMetrics>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional int32 uplink_bandwidth_bps = 1;
    {::_pbi::TcParser::FastV32S1,
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(NetworkMetrics, _impl_.uplink_bandwidth_bps_)}},
    // optional float uplink_packet_loss_fraction = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 1, 0,
      PROTOBUF_FIELD_OFFSET(NetworkMetrics, _impl_.uplink_packet_loss_fraction_)}},
    // optional int32 target_audio_bitrate_bps = 3;
    {::_pbi::TcParser::FastV32S1,
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(NetworkMetrics, _impl_.target_audio_bitrate_bps_)}},
    // optional int32 rtt_ms = 4;
    {::_pbi::TcParser::FastV32S1,
     {32, 3, 0,
      PROTOBUF_FIELD_OFFSET(NetworkMetrics, _impl_.rtt_ms_)}},
    // optional int32 uplink_recoverable_packet_loss_fraction = 5;
    {::_pbi::TcParser::FastV32S1,
     {40, 4, 0,
      PROTOBUF_FIELD_OFFSET(NetworkMetrics, _impl_.uplink_recoverable_packet_loss_fraction_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int32 uplink_bandwidth_bps = 1;
    {PROTOBUF_FIELD_OFFSET(NetworkMetrics, _impl_.uplink_bandwidth_bps_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional float uplink_packet_loss_fraction = 2;
    {PROTOBUF_FIELD_OFFSET(NetworkMetrics, _impl_.uplink_packet_loss_fraction_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional int32 target_audio_bitrate_bps = 3;
    {PROTOBUF_FIELD_OFFSET(NetworkMetrics, _impl_.target_audio_bitrate_bps_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 rtt_ms = 4;
    {PROTOBUF_FIELD_OFFSET(NetworkMetrics, _impl_.rtt_ms_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 uplink_recoverable_packet_loss_fraction = 5;
    {PROTOBUF_FIELD_OFFSET(NetworkMetrics, _impl_.uplink_recoverable_packet_loss_fraction_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void NetworkMetrics::Clear() {
// @@protoc_insertion_point(message_clear_start:webrtc.audio_network_adaptor.debug_dump.NetworkMetrics)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    ::memset(&_impl_.uplink_bandwidth_bps_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.uplink_recoverable_packet_loss_fraction_) -
        reinterpret_cast<char*>(&_impl_.uplink_bandwidth_bps_)) + sizeof(_impl_.uplink_recoverable_packet_loss_fraction_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL NetworkMetrics::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const NetworkMetrics& this_ = static_cast<const NetworkMetrics&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL NetworkMetrics::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const NetworkMetrics& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:webrtc.audio_network_adaptor.debug_dump.NetworkMetrics)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional int32 uplink_bandwidth_bps = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
            stream, this_._internal_uplink_bandwidth_bps(), target);
  }

  // optional float uplink_packet_loss_fraction = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        2, this_._internal_uplink_packet_loss_fraction(), target);
  }

  // optional int32 target_audio_bitrate_bps = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
            stream, this_._internal_target_audio_bitrate_bps(), target);
  }

  // optional int32 rtt_ms = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<4>(
            stream, this_._internal_rtt_ms(), target);
  }

  // optional int32 uplink_recoverable_packet_loss_fraction = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<5>(
            stream, this_._internal_uplink_recoverable_packet_loss_fraction(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:webrtc.audio_network_adaptor.debug_dump.NetworkMetrics)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t NetworkMetrics::ByteSizeLong(const MessageLite& base) {
  const NetworkMetrics& this_ = static_cast<const NetworkMetrics&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t NetworkMetrics::ByteSizeLong() const {
  const NetworkMetrics& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:webrtc.audio_network_adaptor.debug_dump.NetworkMetrics)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += static_cast<bool>(0x00000002U & cached_has_bits) * 5;
  if (BatchCheckHasBit(cached_has_bits, 0x0000001dU)) {
    // optional int32 uplink_bandwidth_bps = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_uplink_bandwidth_bps());
    }
    // optional int32 target_audio_bitrate_bps = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_target_audio_bitrate_bps());
    }
    // optional int32 rtt_ms = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_rtt_ms());
    }
    // optional int32 uplink_recoverable_packet_loss_fraction = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_uplink_recoverable_packet_loss_fraction());
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void NetworkMetrics::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<NetworkMetrics*>(&to_msg);
  auto& from = static_cast<const NetworkMetrics&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:webrtc.audio_network_adaptor.debug_dump.NetworkMetrics)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_impl_.uplink_bandwidth_bps_ = from._impl_.uplink_bandwidth_bps_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.uplink_packet_loss_fraction_ = from._impl_.uplink_packet_loss_fraction_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.target_audio_bitrate_bps_ = from._impl_.target_audio_bitrate_bps_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.rtt_ms_ = from._impl_.rtt_ms_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.uplink_recoverable_packet_loss_fraction_ = from._impl_.uplink_recoverable_packet_loss_fraction_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void NetworkMetrics::CopyFrom(const NetworkMetrics& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:webrtc.audio_network_adaptor.debug_dump.NetworkMetrics)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NetworkMetrics::InternalSwap(NetworkMetrics* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(NetworkMetrics, _impl_.uplink_recoverable_packet_loss_fraction_)
      + sizeof(NetworkMetrics::_impl_.uplink_recoverable_packet_loss_fraction_)
      - PROTOBUF_FIELD_OFFSET(NetworkMetrics, _impl_.uplink_bandwidth_bps_)>(
          reinterpret_cast<char*>(&_impl_.uplink_bandwidth_bps_),
          reinterpret_cast<char*>(&other->_impl_.uplink_bandwidth_bps_));
}

// ===================================================================

class EncoderRuntimeConfig::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<EncoderRuntimeConfig>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(EncoderRuntimeConfig, _impl_._has_bits_);
};

EncoderRuntimeConfig::EncoderRuntimeConfig(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, EncoderRuntimeConfig_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:webrtc.audio_network_adaptor.debug_dump.EncoderRuntimeConfig)
}
EncoderRuntimeConfig::EncoderRuntimeConfig(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const EncoderRuntimeConfig& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, EncoderRuntimeConfig_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE EncoderRuntimeConfig::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void EncoderRuntimeConfig::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, bitrate_bps_),
           0,
           offsetof(Impl_, num_channels_) -
               offsetof(Impl_, bitrate_bps_) +
               sizeof(Impl_::num_channels_));
}
EncoderRuntimeConfig::~EncoderRuntimeConfig() {
  // @@protoc_insertion_point(destructor:webrtc.audio_network_adaptor.debug_dump.EncoderRuntimeConfig)
  SharedDtor(*this);
}
inline void EncoderRuntimeConfig::SharedDtor(MessageLite& self) {
  EncoderRuntimeConfig& this_ = static_cast<EncoderRuntimeConfig&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL EncoderRuntimeConfig::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) EncoderRuntimeConfig(arena);
}
constexpr auto EncoderRuntimeConfig::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(EncoderRuntimeConfig),
                                            alignof(EncoderRuntimeConfig));
}
constexpr auto EncoderRuntimeConfig::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<61>{
      {
          &_EncoderRuntimeConfig_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &EncoderRuntimeConfig::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<EncoderRuntimeConfig>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &EncoderRuntimeConfig::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<EncoderRuntimeConfig>(), &EncoderRuntimeConfig::ByteSizeLong,
              &EncoderRuntimeConfig::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(EncoderRuntimeConfig, _impl_._cached_size_),
          true,
      },
      "webrtc.audio_network_adaptor.debug_dump.EncoderRuntimeConfig",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<61> EncoderRuntimeConfig_class_data_ =
    EncoderRuntimeConfig::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
EncoderRuntimeConfig::GetClassData() const {
  return EncoderRuntimeConfig_class_data_.base();
}
PROTOBUF_CONSTINIT_WITH_PTR PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 0, 0, 2>
EncoderRuntimeConfig::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(EncoderRuntimeConfig, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    EncoderRuntimeConfig_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::webrtc::audio_network_adaptor::debug_dump::EncoderRuntimeConfig>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional int32 bitrate_bps = 1;
    {::_pbi::TcParser::FastV32S1,
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(EncoderRuntimeConfig, _impl_.bitrate_bps_)}},
    // optional int32 frame_length_ms = 2;
    {::_pbi::TcParser::FastV32S1,
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(EncoderRuntimeConfig, _impl_.frame_length_ms_)}},
    // optional float uplink_packet_loss_fraction = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 2, 0,
      PROTOBUF_FIELD_OFFSET(EncoderRuntimeConfig, _impl_.uplink_packet_loss_fraction_)}},
    // optional bool enable_fec = 4;
    {::_pbi::TcParser::FastV8S1,
     {32, 3, 0,
      PROTOBUF_FIELD_OFFSET(EncoderRuntimeConfig, _impl_.enable_fec_)}},
    // optional bool enable_dtx = 5;
    {::_pbi::TcParser::FastV8S1,
     {40, 4, 0,
      PROTOBUF_FIELD_OFFSET(EncoderRuntimeConfig, _impl_.enable_dtx_)}},
    // optional uint32 num_channels = 6;
    {::_pbi::TcParser::FastV32S1,
     {48, 5, 0,
      PROTOBUF_FIELD_OFFSET(EncoderRuntimeConfig, _impl_.num_channels_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int32 bitrate_bps = 1;
    {PROTOBUF_FIELD_OFFSET(EncoderRuntimeConfig, _impl_.bitrate_bps_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 frame_length_ms = 2;
    {PROTOBUF_FIELD_OFFSET(EncoderRuntimeConfig, _impl_.frame_length_ms_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional float uplink_packet_loss_fraction = 3;
    {PROTOBUF_FIELD_OFFSET(EncoderRuntimeConfig, _impl_.uplink_packet_loss_fraction_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional bool enable_fec = 4;
    {PROTOBUF_FIELD_OFFSET(EncoderRuntimeConfig, _impl_.enable_fec_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional bool enable_dtx = 5;
    {PROTOBUF_FIELD_OFFSET(EncoderRuntimeConfig, _impl_.enable_dtx_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional uint32 num_channels = 6;
    {PROTOBUF_FIELD_OFFSET(EncoderRuntimeConfig, _impl_.num_channels_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void EncoderRuntimeConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:webrtc.audio_network_adaptor.debug_dump.EncoderRuntimeConfig)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    ::memset(&_impl_.bitrate_bps_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.num_channels_) -
        reinterpret_cast<char*>(&_impl_.bitrate_bps_)) + sizeof(_impl_.num_channels_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL EncoderRuntimeConfig::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const EncoderRuntimeConfig& this_ = static_cast<const EncoderRuntimeConfig&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL EncoderRuntimeConfig::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const EncoderRuntimeConfig& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:webrtc.audio_network_adaptor.debug_dump.EncoderRuntimeConfig)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional int32 bitrate_bps = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
            stream, this_._internal_bitrate_bps(), target);
  }

  // optional int32 frame_length_ms = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
            stream, this_._internal_frame_length_ms(), target);
  }

  // optional float uplink_packet_loss_fraction = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        3, this_._internal_uplink_packet_loss_fraction(), target);
  }

  // optional bool enable_fec = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        4, this_._internal_enable_fec(), target);
  }

  // optional bool enable_dtx = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        5, this_._internal_enable_dtx(), target);
  }

  // optional uint32 num_channels = 6;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        6, this_._internal_num_channels(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:webrtc.audio_network_adaptor.debug_dump.EncoderRuntimeConfig)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t EncoderRuntimeConfig::ByteSizeLong(const MessageLite& base) {
  const EncoderRuntimeConfig& this_ = static_cast<const EncoderRuntimeConfig&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t EncoderRuntimeConfig::ByteSizeLong() const {
  const EncoderRuntimeConfig& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:webrtc.audio_network_adaptor.debug_dump.EncoderRuntimeConfig)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += static_cast<bool>(0x00000004U & cached_has_bits) * 5;
  total_size += ::absl::popcount(0x00000018U & cached_has_bits) * 2;
  if (BatchCheckHasBit(cached_has_bits, 0x00000023U)) {
    // optional int32 bitrate_bps = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_bitrate_bps());
    }
    // optional int32 frame_length_ms = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_frame_length_ms());
    }
    // optional uint32 num_channels = 6;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_num_channels());
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void EncoderRuntimeConfig::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<EncoderRuntimeConfig*>(&to_msg);
  auto& from = static_cast<const EncoderRuntimeConfig&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:webrtc.audio_network_adaptor.debug_dump.EncoderRuntimeConfig)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_impl_.bitrate_bps_ = from._impl_.bitrate_bps_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.frame_length_ms_ = from._impl_.frame_length_ms_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.uplink_packet_loss_fraction_ = from._impl_.uplink_packet_loss_fraction_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.enable_fec_ = from._impl_.enable_fec_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.enable_dtx_ = from._impl_.enable_dtx_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      _this->_impl_.num_channels_ = from._impl_.num_channels_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void EncoderRuntimeConfig::CopyFrom(const EncoderRuntimeConfig& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:webrtc.audio_network_adaptor.debug_dump.EncoderRuntimeConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EncoderRuntimeConfig::InternalSwap(EncoderRuntimeConfig* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(EncoderRuntimeConfig, _impl_.num_channels_)
      + sizeof(EncoderRuntimeConfig::_impl_.num_channels_)
      - PROTOBUF_FIELD_OFFSET(EncoderRuntimeConfig, _impl_.bitrate_bps_)>(
          reinterpret_cast<char*>(&_impl_.bitrate_bps_),
          reinterpret_cast<char*>(&other->_impl_.bitrate_bps_));
}

// ===================================================================

class Event::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Event>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Event, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000018) ^ 0x00000018) != 0;
  }
};

void Event::clear_controller_manager_config() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.controller_manager_config_ != nullptr) _impl_.controller_manager_config_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
Event::Event(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, Event_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:webrtc.audio_network_adaptor.debug_dump.Event)
}
PROTOBUF_NDEBUG_INLINE Event::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::webrtc::audio_network_adaptor::debug_dump::Event& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

Event::Event(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Event& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, Event_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Event* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.network_metrics_ = (CheckHasBit(cached_has_bits, 0x00000001U))
                ? ::google::protobuf::MessageLite::CopyConstruct(arena, *from._impl_.network_metrics_)
                : nullptr;
  _impl_.encoder_runtime_config_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::MessageLite::CopyConstruct(arena, *from._impl_.encoder_runtime_config_)
                : nullptr;
  _impl_.controller_manager_config_ = (CheckHasBit(cached_has_bits, 0x00000004U))
                ? ::google::protobuf::MessageLite::CopyConstruct(arena, *from._impl_.controller_manager_config_)
                : nullptr;
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, type_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, type_),
           offsetof(Impl_, timestamp_) -
               offsetof(Impl_, type_) +
               sizeof(Impl_::timestamp_));

  // @@protoc_insertion_point(copy_constructor:webrtc.audio_network_adaptor.debug_dump.Event)
}
PROTOBUF_NDEBUG_INLINE Event::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void Event::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, network_metrics_),
           0,
           offsetof(Impl_, timestamp_) -
               offsetof(Impl_, network_metrics_) +
               sizeof(Impl_::timestamp_));
}
Event::~Event() {
  // @@protoc_insertion_point(destructor:webrtc.audio_network_adaptor.debug_dump.Event)
  SharedDtor(*this);
}
inline void Event::SharedDtor(MessageLite& self) {
  Event& this_ = static_cast<Event&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.network_metrics_;
  delete this_._impl_.encoder_runtime_config_;
  delete this_._impl_.controller_manager_config_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Event::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Event(arena);
}
constexpr auto Event::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Event),
                                            alignof(Event));
}
constexpr auto Event::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<46>{
      {
          &_Event_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          Event::IsInitializedImpl,
          &Event::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<Event>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Event::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<Event>(), &Event::ByteSizeLong,
              &Event::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Event, _impl_._cached_size_),
          true,
      },
      "webrtc.audio_network_adaptor.debug_dump.Event",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<46> Event_class_data_ =
    Event::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Event::GetClassData() const {
  return Event_class_data_.base();
}
PROTOBUF_CONSTINIT_WITH_PTR PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 4, 0, 2>
Event::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Event, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    4,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Event_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::webrtc::audio_network_adaptor::debug_dump::Event>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // required .webrtc.audio_network_adaptor.debug_dump.Event.Type type = 1;
    {::_pbi::TcParser::FastEr0S1,
     {8, 3, 2,
      PROTOBUF_FIELD_OFFSET(Event, _impl_.type_)}},
    // required uint32 timestamp = 2;
    {::_pbi::TcParser::FastV32S1,
     {16, 4, 0,
      PROTOBUF_FIELD_OFFSET(Event, _impl_.timestamp_)}},
    // optional .webrtc.audio_network_adaptor.debug_dump.NetworkMetrics network_metrics = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 0, 0,
      PROTOBUF_FIELD_OFFSET(Event, _impl_.network_metrics_)}},
    // optional .webrtc.audio_network_adaptor.debug_dump.EncoderRuntimeConfig encoder_runtime_config = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 1, 1,
      PROTOBUF_FIELD_OFFSET(Event, _impl_.encoder_runtime_config_)}},
    // optional .webrtc.audio_network_adaptor.config.ControllerManager controller_manager_config = 5;
    {::_pbi::TcParser::FastMtS1,
     {42, 2, 2,
      PROTOBUF_FIELD_OFFSET(Event, _impl_.controller_manager_config_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // required .webrtc.audio_network_adaptor.debug_dump.Event.Type type = 1;
    {PROTOBUF_FIELD_OFFSET(Event, _impl_.type_), _Internal::kHasBitsOffset + 3, 3, (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
    // required uint32 timestamp = 2;
    {PROTOBUF_FIELD_OFFSET(Event, _impl_.timestamp_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional .webrtc.audio_network_adaptor.debug_dump.NetworkMetrics network_metrics = 3;
    {PROTOBUF_FIELD_OFFSET(Event, _impl_.network_metrics_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .webrtc.audio_network_adaptor.debug_dump.EncoderRuntimeConfig encoder_runtime_config = 4;
    {PROTOBUF_FIELD_OFFSET(Event, _impl_.encoder_runtime_config_), _Internal::kHasBitsOffset + 1, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .webrtc.audio_network_adaptor.config.ControllerManager controller_manager_config = 5;
    {PROTOBUF_FIELD_OFFSET(Event, _impl_.controller_manager_config_), _Internal::kHasBitsOffset + 2, 2, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::webrtc::audio_network_adaptor::debug_dump::NetworkMetrics>()},
      {::_pbi::TcParser::GetTable<::webrtc::audio_network_adaptor::debug_dump::EncoderRuntimeConfig>()},
      {::_pbi::TcParser::GetTable<::webrtc::audio_network_adaptor::config::ControllerManager>()},
      {0, 2},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void Event::Clear() {
// @@protoc_insertion_point(message_clear_start:webrtc.audio_network_adaptor.debug_dump.Event)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(_impl_.network_metrics_ != nullptr);
      _impl_.network_metrics_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.encoder_runtime_config_ != nullptr);
      _impl_.encoder_runtime_config_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(_impl_.controller_manager_config_ != nullptr);
      _impl_.controller_manager_config_->Clear();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000018U)) {
    ::memset(&_impl_.type_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.timestamp_) -
        reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.timestamp_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Event::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Event& this_ = static_cast<const Event&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Event::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Event& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:webrtc.audio_network_adaptor.debug_dump.Event)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // required .webrtc.audio_network_adaptor.debug_dump.Event.Type type = 1;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this_._internal_type(), target);
  }

  // required uint32 timestamp = 2;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this_._internal_timestamp(), target);
  }

  // optional .webrtc.audio_network_adaptor.debug_dump.NetworkMetrics network_metrics = 3;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.network_metrics_, this_._impl_.network_metrics_->GetCachedSize(), target,
        stream);
  }

  // optional .webrtc.audio_network_adaptor.debug_dump.EncoderRuntimeConfig encoder_runtime_config = 4;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, *this_._impl_.encoder_runtime_config_, this_._impl_.encoder_runtime_config_->GetCachedSize(), target,
        stream);
  }

  // optional .webrtc.audio_network_adaptor.config.ControllerManager controller_manager_config = 5;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        5, *this_._impl_.controller_manager_config_, this_._impl_.controller_manager_config_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:webrtc.audio_network_adaptor.debug_dump.Event)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Event::ByteSizeLong(const MessageLite& base) {
  const Event& this_ = static_cast<const Event&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Event::ByteSizeLong() const {
  const Event& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:webrtc.audio_network_adaptor.debug_dump.Event)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // optional .webrtc.audio_network_adaptor.debug_dump.NetworkMetrics network_metrics = 3;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.network_metrics_);
    }
    // optional .webrtc.audio_network_adaptor.debug_dump.EncoderRuntimeConfig encoder_runtime_config = 4;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.encoder_runtime_config_);
    }
    // optional .webrtc.audio_network_adaptor.config.ControllerManager controller_manager_config = 5;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.controller_manager_config_);
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000018U)) {
    // required .webrtc.audio_network_adaptor.debug_dump.Event.Type type = 1;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
    }
    // required uint32 timestamp = 2;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_timestamp());
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void Event::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Event*>(&to_msg);
  auto& from = static_cast<const Event&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:webrtc.audio_network_adaptor.debug_dump.Event)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(from._impl_.network_metrics_ != nullptr);
      if (_this->_impl_.network_metrics_ == nullptr) {
        _this->_impl_.network_metrics_ = ::google::protobuf::MessageLite::CopyConstruct(arena, *from._impl_.network_metrics_);
      } else {
        _this->_impl_.network_metrics_->MergeFrom(*from._impl_.network_metrics_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.encoder_runtime_config_ != nullptr);
      if (_this->_impl_.encoder_runtime_config_ == nullptr) {
        _this->_impl_.encoder_runtime_config_ = ::google::protobuf::MessageLite::CopyConstruct(arena, *from._impl_.encoder_runtime_config_);
      } else {
        _this->_impl_.encoder_runtime_config_->MergeFrom(*from._impl_.encoder_runtime_config_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(from._impl_.controller_manager_config_ != nullptr);
      if (_this->_impl_.controller_manager_config_ == nullptr) {
        _this->_impl_.controller_manager_config_ = ::google::protobuf::MessageLite::CopyConstruct(arena, *from._impl_.controller_manager_config_);
      } else {
        _this->_impl_.controller_manager_config_->MergeFrom(*from._impl_.controller_manager_config_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.type_ = from._impl_.type_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.timestamp_ = from._impl_.timestamp_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void Event::CopyFrom(const Event& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:webrtc.audio_network_adaptor.debug_dump.Event)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Event::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const Event&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  return true;
}

void Event::InternalSwap(Event* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Event, _impl_.timestamp_)
      + sizeof(Event::_impl_.timestamp_)
      - PROTOBUF_FIELD_OFFSET(Event, _impl_.network_metrics_)>(
          reinterpret_cast<char*>(&_impl_.network_metrics_),
          reinterpret_cast<char*>(&other->_impl_.network_metrics_));
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace debug_dump
}  // namespace audio_network_adaptor
}  // namespace webrtc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
